import React, { useState } from 'react';
import { Upload, Save } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Image } from '@/components/ui/image';
import { categories, productImage } from '@/components/burger/catalog';
import Overlay from '@/components/burger/Overlay';
export default function ProductForm({ product, onClose, onSaved }) {
  const [form, setForm] = useState(product || { name: '', description: '', price: '', category: 'Hambúrgueres', ingredients: [], image_url: '', badge: '', active: true });
  const [ingredients, setIngredients] = useState((product?.ingredients || []).join(', ')), [busy, setBusy] = useState(false), [uploading, setUploading] = useState(false), [error, setError] = useState('');
  const change = (key, value) => setForm(f => ({ ...f, [key]: value }));
  const upload = async e => { const file = e.target.files[0]; if (!file) return; setUploading(true); setError(''); try { const { file_url } = await base44.integrations.Core.UploadPublicFile({ file }); change('image_url', file_url); } catch { setError('Não foi possível enviar a foto.'); } finally { setUploading(false); } };
  const submit = async e => { e.preventDefault(); if (!productImage(form)) { setError('Adicione uma foto do produto.'); return; } setBusy(true); setError(''); try { const data = { name: form.name, description: form.description, price: Number(form.price), category: form.category, ingredients: ingredients.split(',').map(x => x.trim()).filter(Boolean), image_url: form.image_url || '', image_key: form.image_key || '', badge: form.badge || '', active: form.active }; if (product) await base44.entities.Product.update(product.id, data); else await base44.entities.Product.create(data); onSaved(); onClose(); } catch { setError('Não foi possível salvar o produto.'); } finally { setBusy(false); } };
  return <Overlay title={product ? 'EDITAR PRODUTO' : 'NOVO PRODUTO'} onClose={onClose}><form onSubmit={submit} className="form-body"><label className="upload-box">{productImage(form) && <Image src={productImage(form)} alt="Foto do produto" className="admin-preview" />}<Upload size={21} /><span>{uploading ? 'Enviando foto…' : 'Escolher foto do produto'}</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading} /></label><small className="muted">Foto pública, exibida no cardápio.</small><label className="field">Nome<input required value={form.name} onChange={e => change('name', e.target.value)} /></label><label className="field">Descrição<textarea required value={form.description} onChange={e => change('description', e.target.value)} /></label><div className="form-grid"><label className="field">Preço (R$)<input required type="number" min="0.01" step="0.01" value={form.price} onChange={e => change('price', e.target.value)} /></label><label className="field">Categoria<select value={form.category} onChange={e => change('category', e.target.value)}>{categories.slice(1).map(c => <option key={c}>{c}</option>)}</select></label></div><label className="field">Ingredientes removíveis (separados por vírgula)<input value={ingredients} onChange={e => setIngredients(e.target.value)} /></label><label className="field">Etiqueta (opcional)<input placeholder="Ex.: MAIS PEDIDO" value={form.badge || ''} onChange={e => change('badge', e.target.value)} /></label><label className="check-row"><input type="checkbox" checked={form.active} onChange={e => change('active', e.target.checked)} /> Disponível no cardápio</label>{error && <p className="error-text" role="alert">{error}</p>}<button className="primary-btn" disabled={busy || uploading}><Save size={17} />{busy ? 'SALVANDO…' : 'SALVAR PRODUTO'}</button></form></Overlay>;
}