import React, { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Send, MessageCircle } from 'lucide-react';
import { base44 } from '@/api/base44Client';
export default function SupportInbox() {
  const client = useQueryClient(), [selected, setSelected] = useState(''), [text, setText] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const { data: messages = [], isLoading } = useQuery({ queryKey: ['admin-messages'], queryFn: () => base44.entities.SupportMessage.list('created_date', 1000), refetchInterval: 10000 });
  useEffect(() => base44.entities.SupportMessage.subscribe(() => client.invalidateQueries({ queryKey: ['admin-messages'] })), [client]);
  const sessions = [...new Set(messages.filter(m => m.sender === 'customer').map(m => m.session))];
  const active = selected || sessions[0];
  const send = async e => { e.preventDefault(); if (!text.trim()) return; setBusy(true); setError(''); try { await base44.entities.SupportMessage.create({ session: active, sender: 'staff', text: text.trim() }); setText(''); client.invalidateQueries({ queryKey: ['admin-messages'] }); } catch { setError('Não foi possível enviar. Tente novamente.'); } finally { setBusy(false); } };
  return isLoading ? <div className="empty-state">Carregando atendimento…</div> : !sessions.length ? <div className="empty-state"><MessageCircle size={35} /><h3>Nenhuma conversa por enquanto</h3><p>As mensagens do chat da loja aparecem aqui.</p></div> : <div className="support-inbox"><aside>{sessions.map(s => <button key={s} className={s === active ? 'active' : ''} onClick={() => setSelected(s)}>Cliente #{s.slice(-6)}<small>{messages.filter(m => m.session === s).at(-1)?.text}</small></button>)}</aside><div className="support-conversation"><h3>ATENDIMENTO #{active.slice(-6).toUpperCase()}</h3><div className="support-messages">{messages.filter(m => m.session === active).map(m => <div className={`chat-bubble ${m.sender}`} key={m.id}>{m.text}<small>{m.sender === 'staff' ? 'Equipe Best Burguer 013' : 'Cliente'} • {new Date(m.created_date).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</small></div>)}</div><form className="chat-input" onSubmit={send}><input aria-label="Resposta ao cliente" value={text} onChange={e => setText(e.target.value)} placeholder="Responder ao cliente…" maxLength={1000} /><button disabled={busy || !text.trim()} aria-label="Enviar resposta"><Send size={20} /></button></form>{error && <p className="error-text">{error}</p>}</div></div>;
}